name: Build and Test

on:
  push:
    paths:
      - 'Sources/**'
      - 'Tests/**'
      - '.github/workflows/**'
      - '!Sources/VanMoofKit/Documentation.docc/**'
  pull_request:
    paths:
      - 'Sources/**'
      - 'Tests/**'
      - '.github/workflows/**'
      - '!Sources/VanMoofKit/Documentation.docc/**'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
